plugins {  
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'  
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'  
}  
  
apply from: 'https://raw.githubusercontent.com/Crimix/bml/1.20/shadow.gradle'  
  
version = version_major + '.' + version_minor + '.' + version_patch  
group = mod_group  
base {  
    archivesName = mod_archivesBaseName + "-" + mc_version  
}  
  
java.toolchain.languageVersion = JavaLanguageVersion.of(17)  
  
println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))  
  
minecraft {  
    mappings channel: mappings_channel, version: mappings_version  
    copyIdeResources = true  
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')  
  
    runs {  
        client {  
            workingDirectory project.file('run')  
            property 'forge.logging.markers', 'REGISTRIES'  
            property 'forge.logging.console.level', 'debug'  
            property 'mixin.env.disableRefMap', 'true'  
            property 'forge.enabledGameTestNamespaces', mod_id  
            mods {  
                "${mod_id}" { source sourceSets.main }  
            }  
        }  
        server {  
            workingDirectory project.file('run')  
            property 'forge.logging.markers', 'REGISTRIES'  
            property 'forge.logging.console.level', 'debug'  
            property 'mixin.env.disableRefMap', 'true'  
            property 'forge.enabledGameTestNamespaces', mod_id
            mods {  
                "${mod_id}" { source sourceSets.main }  
            }  
        }  
    }  
}  
  
repositories {  
    maven { url = 'https://maven.parchmentmc.org' }  
    maven {  
        name = "Progwml6 maven"  
        url = "https://dvs1.progwml6.com/files/maven/"  
    }  
    maven {  
        name = "ModMaven"  
        url = "https://modmaven.k-4u.nl"  
    }  
    mavenLocal()  
}  
  
dependencies {  
    minecraft "net.minecraftforge:forge:${project.mc_version}-${project.forge_version}"  
  
    implementation fg.deobf("curse.maven:jade-324717:${jade_version}") {  
        transitive = false  
    }
  
    shadowCompileOnly fg.deobf(files('libs/bml-1.20-1.1.8-b1.jar'))  
    runtimeOnly fg.deobf(files('libs/bml-1.20-1.1.8-b1.jar'))  
}  
  
jar {  
    manifest {  
        attributes(["Specification-Title"     : "tabstats",  
                    "Specification-Vendor"     : "black_dog20",  
                    "Specification-Version"    : "1",  
                    "Implementation-Title"     : "Tab Stats",  
                    "Implementation-Version"   : archiveVersion.get(),  
                    "Implementation-Vendor"    : "black_dog20",  
                    "Implementation-Timestamp" : new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")],)  
    }  
}  
  
shadowJar {  
    configurations = [project.configurations.shadowCompileOnly]  
    relocate 'com.black_dog20.bml', 'com.black_dog20.tabstats.repack.bml'  
}